image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

build_web:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/test/web" -f Dockerfile.web .
    - docker push "$CI_REGISTRY_IMAGE/test/web"
    - docker tag "$CI_REGISTRY_IMAGE/test/web" "$CI_REGISTRY_IMAGE/test/web:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE/test/web:$CI_COMMIT_REF_NAME"
  only:
    - tags

build_varnish:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    # build varnish image
    - docker build --pull -t "$CI_REGISTRY_IMAGE/test/varnish" -f Dockerfile.varnish .
    - docker push "$CI_REGISTRY_IMAGE/test/varnish"
    - docker tag "$CI_REGISTRY_IMAGE/test/varnish" "$CI_REGISTRY_IMAGE/test/varnish:$CI_COMMIT_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE/test/varnish:$CI_COMMIT_REF_NAME"
  only:
    - tags

deploy_web:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack integ-alod-ch --service web --new-image $CI_REGISTRY_IMAGE/test/web:$CI_COMMIT_REF_NAME
  only:
    - tags

deploy_varnish:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --environment default --stack integ-alod-ch --service varnish --new-image $CI_REGISTRY_IMAGE/test/varnish:$CI_COMMIT_REF_NAME
  only:
    - tags
